# Configuration file for Travis CI test environment
language: php
php:
  - 5.3

# Don't build feature branches etc, as they will be covered by PRs
branches:
  only:
    - /^[0-9\.]+\.x$/

before_script:
  # Ensure composer is up to date and install dependencies
  - composer self-update
  - composer install --dev
  # Generate the koharness Kohana default application
  - vendor/bin/koharness


# Run the View tests against the koharnessed application in /tmp/koharness
script: cd /tmp/koharness && phpunit --bootstrap=modules/unittest/bootstrap.php --group=view_model modules/unittest/tests.php
